### ISSUE TITLE
Mantis - Mediawiki single sign-on

### ISSUE THREAD

**Issue by ronlinet** [tessus/mwExtensionMantis#11]
Does your plugin include any mechanism to  honour Mantis authentication (i.e. single sign-on).
Thx.

**Comment by tessus** [comment]
This topic is a rather complex one. My extension allows you to display a list of Mantis tickets and filter/restrict the result set by certain criteria. It does not allow you to modify Mantis content thus I never even considered a user authentication.
Why would you need a single sign-on for displaying tickets? Or do you want to click on a bug id and then automatically be logged in to Mantis? Mediawiki and MantisBT use a different user system and unless MantisBT would allow to map MW users to MantisBT users I don't see a way to make this work.
The plugin cannot map users and manage authentcation tokens for both systems.

But I'm open to suggestions. If you have a use case, I can think about the feasibility of such an endeavor.

**Comment by tessus** [comment]
@ronlinet any follow up on this topic or can I close the ticket?

**Comment by ronlinet** [comment]
The suggestion would be to use the same authentication approach as for dokuwiki => https://www.mantisbt.org/wiki/doku.php/mantisbt:issue:7075:integration_with_dokuwiki .

**Comment by tessus** [comment]
@ronlinet I've looked into your suggestion, but the changes required are too extensive for this plugin.
One of the issues is that I would have to change MediaWiki core code and I am not a mw core dev. If you can get the required changes into mw, I can adjust the plugin to make use of them.

**Comment by ronlinet** [comment]
Hi Helmut, 
Another option is to go for a different wiki engine. 
I have been using mw in 2009 and  I have turn away because of lack of granular access control. 
MW is an excellent project but if you use it as a collaborative tool you will end up with  requirements to attribute specific access to specific parts to specific users and here will is were MW fails. I am trying to focus now on dokuwiki as it seems to be the most appropriate tool to clinch within mantisbt. I have opened a topic about this if you want you can join us here => http://mantisbt.org/bugs/view.php?id=21141 .

**Comment by tessus** [comment]
Yes, this would be an option, but in that case I would also have to maintain more than one Mantis plugin. I agree that MW has a lack of granular access control, but it has been sufficient for me so far. 
I wrote this plugin, because I wanted to show open and high sev tickets right on the project wiki page for a few people who worked on a common project. The existing one was rather out of date and was missing a few features.
My code is licensed under GPL-2, which is compatible with Mantis and docuwiki. It shouldn't be too complicated to rewrite it for docuwiki. Unfortunately I don't have the time to learn docuwiki and how to write plugins for it. But if you had any specific questions about what my code does, I'd be happy to answer them.
