### ISSUE TITLE
display as plain-text, not table ?

### ISSUE THREAD

**Issue by ka7** [tessus/mwExtensionMantis#35]
Hi,

first: great tool, it was one of the must-haves to choose mantis as our ticket-system. (we use pure mediakwiki much longer)

I have a case, where i want display the status (of a mantis-bug) within a wiki-table.
( the wiki-table is a kind of overall tracking for stuff, some things have also a bug assigned, for cross-link purpose )

It would be nice if there's an option to display as "text", not "HTML table" ( but keep the "strike" if done ... )

( later, i have a script reading wiki and mantis to generate a "whats ongoing" email; at least here the sub-table is a brainer (via py-pandas); and also viewing the rendered page is not a beauty )

technically, i could think of something like a "output_format = table" ( = default, to keep the world running ) and "no_table" as valid option.

.. sounds like a plan ? (if yes, i could also do some coding and do a pull-request)

as a second example, I've seen things (in other systems) in a wiki-doku like: "feature xy cant currently be implemented, because of lib-abc does currently not support this (#123 - assigned(xy) )  " 
( this "123, assigned" would come in that case from this plugin, but in a non-html-table way. )

.ka7

**Comment by ka7** [comment]
.. something like this:

https://github.com/ka7/mwExtensionMantis/tree/feature__no_table

(its not tested, as i have currently have no access to mediawiki/mantis system)

.. it introduces new config-option "output_format = table|no_table" ( table is default, even if not set)
the "no_table" should print just plain-text #

**Comment by tessus** [comment]
Hmm, I think we need a better spec for how to handle this. It could make sense, if the result set were 1 column and 1 row (one singular value), but for everything else this is going to be a mess.

If it's not a a table, the output will all be jumbled together. I don't think this makes any sense.

> ( but keep the "strike" if done ... )

I don't know what the means.

> I have a case, where i want display the status (of a mantis-bug) within a wiki-table.

This might be ok for one single bug, but if you were to use this for a lot of bugs, every time you'd invoke the extension, a statement is run. This is probably the worst runtime ever.

> the wiki-table is a kind of overall tracking for stuff, some things have also a bug assigned, for cross-link purpose

This is exactlly what my extension is for. If you want to add other stuff to the result set, you can use the `comment` feature.
It seems you want to create your own table and call the extension for every row in "your" table. This is wrong, at least that's not why I created this extension.

> feature xy cant currently be implemented, because of lib-abc does currently not support this (#123 - assigned(xy) 

This is exactly my point. You got it backwards. In this case, you'd retrieve a table of open/assigned/whatever bugs and add a comment to bug x.
comment.x = feature xy cant currently be implemented, because of lib-abc does currently not support this

I am rather reluctant to add code to this extension if it means it will decrease performance and overall experience. I will also have to maintain this code in the future.

I'm currently not convinced that this "feature" is a feature but rather a workaround for a very uncommon niche case. Maybe you can change my mind, but I don't see any benefit.
